### ISSUE TITLE
Update cookie message to `o-cookie-message`

### ISSUE THREAD

**Issue by notlee** [Financial-Times/n-messaging-client#133]
We have a component for the cookie message which is used across other FT Group products. It would be great to integrate into `n-messaging-client`: https://registry.origami.ft.com/components/o-cookie-message

Current `n-messaging-client` implementation:
<img width="502" alt="screenshot 2019-01-04 at 12 36 32" src="https://user-images.githubusercontent.com/10405691/50688633-3d003d80-101e-11e9-8afd-f736549d033c.png">

`o-cookie-message`:
<img width="405" alt="screenshot 2019-01-04 at 12 43 22" src="https://user-images.githubusercontent.com/10405691/50688663-57d2b200-101e-11e9-84cf-a2633b02e0ac.png">

**Comment by bjfletcher** [comment]
hey @notlee, it makes a lot of sense for all FT sites to have a common cookie consent banner

looking at the o-cookie-message doc, it looks like it's a dynamically generated banner (using JS)

currently n-messaging-client renders the cookie banner server-side, so that people with no/broken JS will still see the cookie consent banner

so, a question for you here would be: how to best render the o-cookie-message banner server-side?

**Comment by notlee** [comment]
Thanks for looking into it @bjfletcher! That's a very good question. You're able to add the full cookie message markup and `o-cookie-message` will attach to that if JavaScript is available. I've updated the readme to be much more clear :)
https://registry.origami.ft.com/components/o-cookie-message@5.0.3/readme?brand=master#core-experience-cookie-message
